coverage:
  range: 50..75
  round: up
  precision: 2

  status:
    project: no
    patch: yes
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "**/*-test.cpp"  # ignore test harness code
  - "**/detail"
  - "**/config"
  - "**/meta"
  - "**/foundation/utility"
  - "**/foundation/logging"
  - "**/foundation/memory/allocator_traits.hpp"
  - "**/foundation/memory/addressof.hpp"
  - "**/foundation/memory/construct_at.hpp"
  - "**/foundation/memory/debugging.*"
  - "**/foundation/memory/deleter.hpp"
  - "**/foundation/memory/launder.hpp"
  - "**/foundation/memory/memory_block.hpp"
  - "**/foundation/memory/memory_pool_type.hpp"
  - "**/foundation/memory/temporary_allocator.*"
  - "**/foundation/memory/threading.hpp"