coverage:
  range: 50..75
  round: up
  precision: 2

  status:
    project: no
    patch: yes
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "**/*-test.cpp"  # ignore test harness code
  - "**/detail"
  - "**/config"
  - "**/logging"
  - "**/meta"
  - "**/foundation/abort.hpp"
  - "**/foundation/addressof.hpp"
  - "**/foundation/allocator_traits.hpp"
  - "**/foundation/addressof.hpp"
  - "**/foundation/construct_at.hpp"
  - "**/foundation/debugging.*"
  - "**/foundation/default_allocator.hpp"
  - "**/foundation/deleter.hpp"
  - "**/foundation/launder.hpp"
  - "**/foundation/memory_block.hpp"
  - "**/foundation/memory_pool_type.hpp"
  - "**/foundation/temporary_allocator.*"
  - "**/foundation/terminate.hpp"
  - "**/foundation/threading.hpp"
  - "**/foundation/types.hpp"
  - "**/foundation/unreachable.hpp"