#pragma once

#ifdef SALT_TARGET_OPENGL
#    define SALT_OPENGL_FULL_VERSION SALT_JOIN(SALT_OPENGL_VERSION_MAJOR, SALT_JOIN(SALT_OPENGL_VERSION_MINOR, 0))
#    define SALT_GLSL_VERSION "#version " SALT_TO_STRING(SALT_OPENGL_FULL_VERSION)
#endif