#pragma once

#define SALT_LOGGING_ENABLE_TRACE   (1)
#define SALT_LOGGING_ENABLE_DEBUG   (1)
#define SALT_LOGGING_ENABLE_WARNING (1)
#define SALT_LOGGING_ENABLE_ERROR   (1)
#define SALT_LOGGING_ENABLE_ALL     (1)

#define SALT_LOGGING_ENABLED(LOG_LEVEL) SALT_JOIN(SALT_LOGGING_ENABLE_, LOG_LEVEL)

#define SALT_LOGGING_FORCE_TO_FILE   (0)