#pragma once

// clang-format off
#define _SALT_JOIN(a, b) a##b
#define  SALT_JOIN(a, b) _SALT_JOIN(a, b)

#define SALT_UNIQUE_NAME(base) SALT_JOIN(base, __COUNTER__)

#define _SALT_TO_STRING(x) #x
#define  SALT_TO_STRING(x) _SALT_TO_STRING(x)

#define SALT_EVAL(...) __VA_ARGS__
#define SALT_FIRST(X,...) X
#define SALT_TAIL(X,...) __VA_ARGS__

#define  SALT_VARCOUNT(...) SALT_EVAL(_SALT_VARCOUNT(__VA_ARGS__, 9, 8, 7, 6, 5, 4, 3, 2, 1,))
#define _SALT_VARCOUNT(_, _9, _8, _7, _6, _5, _4, _3, _2, X_,...) X_

#define SALT_TRANSFORM(FUNC, ...) SALT_JOIN(SALT_TRANSFORM_,SALT_VARCOUNT(__VA_ARGS__))(FUNC,__VA_ARGS__)
#define SALT_TRANSFORM_1(FUNC, ...) FUNC(__VA_ARGS__)
#define SALT_TRANSFORM_2(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_1(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_3(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_2(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_4(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_3(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_5(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_4(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_6(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_5(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_7(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_6(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_8(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_7(FUNC, SALT_TAIL(__VA_ARGS__))
#define SALT_TRANSFORM_9(FUNC, ...) FUNC(SALT_FIRST(__VA_ARGS__)), SALT_TRANSFORM_8(FUNC, SALT_TAIL(__VA_ARGS__))
// clang-format on