name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest]
        compiler:
          - { pkg: clang, exe: 'clang++', version: 16 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.26.3
          ninjaVersion: 1.11.1

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.compiler.pkg }}-${{ matrix.compiler.version }}

      - name: Configure
        env:
          CXX: ${{ matrix.compiler.exe }}-${{ matrix.compiler.version }}
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSALT_GRAPHICS=OpenGL -S . -B ${{github.workspace}}/build -G Ninja

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
